### ISSUE TITLE
Container Fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by thomasalley** [jose-delarosa/docker-images#3]
Following instructions from README on a fresh Ubuntu 14.04 Docker install. Container fails to start and goes into Restarting numerous times before eventually stopping. Here's a snip from `docker logs`

> DSM SA Shared Services is already stopped
> Shutting down DSM SA Connection Service: [FAILED]
> 
> Stopping Systems Management Data Engine:
> Stopping dsm_sa_snmpd: Not started[FAILED]
> Stopping dsm_sa_eventmgrd: Not started[FAILED]
> Stopping dsm_sa_datamgrd: Not started[FAILED]
> Stopping Systems Management Device Drivers:
> Stopping dcdbas:[  OK  ]
> Stopping dell_rbu:[  OK  ]
> Starting Systems Management Device Drivers:
> Starting dcdbas:[  OK  ]
> Starting dell_rbu:[  OK  ]
> Starting Systems Management Data Engine:
> Failed to start because system is not supported
> dsm_om_shrsvc: DSM SA Shared Services cannot start on an unsupported system. See the Dell Systems Software Support Matrix for a list of supported systems.
> touch: cannot touch ‘/var/lock/subsys/dsm_om_connsvc’: No such file or directory
> Starting DSM SA Connection Service: [  OK  ]
> tail: cannot open '/opt/dell/srvadmin/var/log/openmanage/dcsys64.xml' for reading: No such file or directory
> tail: no files remaining

I tried building from the Dockerfile as well, with the same results.

**Comment by jose-delarosa** [comment]
ACKed. I'll take a look. Thanks.

**Comment by jose-delarosa** [comment]
@thomasalley just tested existing image on older PowerEdge server using Ubuntu 14.04.4 and worked as expected, no issues. I am using docker v1.9.1. Below is the output you should be seeing:

```
# docker logs -f omsa81
DSM SA Shared Services is already stopped
DSM SA Connection Service is already stopped
Stopping Systems Management Data Engine:
Stopping dsm_sa_snmpd: Not started[FAILED]
Stopping dsm_sa_eventmgrd: Not started[FAILED]
Stopping dsm_sa_datamgrd: Not started[FAILED]
Stopping Systems Management Device Drivers:
Stopping dell_rbu: Not started[  OK  ]
Starting Systems Management Device Drivers:
Starting dell_rbu:[  OK  ]
Starting ipmi driver:
Already started[  OK  ]
Starting Systems Management Data Engine:
Starting dsm_sa_datamgrd: [  OK  ]
Starting dsm_sa_eventmgrd: [  OK  ]
Starting dsm_sa_snmpd: [  OK  ]
touch: cannot touch ‘/var/lock/subsys/dsm_om_shrsvc’: No such file or directory
Starting DSM SA Shared Services: [  OK  ]
tput: No value for $TERM and no -T specified
touch: cannot touch ‘/var/lock/subsys/dsm_om_connsvc’: No such file or directory
Starting DSM SA Connection Service: [  OK  ]
<?xml version="1.0" encoding="UTF-8"?><EventLog><LogEntry><TimeStamp>1458660202</TimeStamp><DateTime>Tue Mar 22 15:23:22 2016</DateTime><ComputerName>060bc5d90f3e</ComputerName><Type>4</Type><ID>1000</ID><Link>help/hip/en/msgguide/wwhelp/wwhimpl/common/html/wwhelp.htm?context=Messages_Guide&amp;topic=1000</Link><UserInfo></UserInfo><Source>Server_Administrator</Source><Category>Instrumentation Service</Category><Description>Server Administrator starting</Description><Data></Data></LogEntry><LogEntry><TimeStamp>1458660202</TimeStamp><DateTime>Tue Mar 22 15:23:22 2016</DateTime><ComputerName>060bc5d90f3e</ComputerName><Type>4</Type><ID>1012</ID><Link>help/hip/en/msgguide/wwhelp/wwhimpl/common/html/wwhelp.htm?context=Messages_Guide&amp;topic=1012</Link><UserInfo></UserInfo><Source>Server_Administrator</Source><Category>Instrumentation Service</Category><Description>IPMI status
ERROR: Another copy of the Inventory Collector is running. Please wait until it is complete. Terminating
tput: No value for $TERM and no -T specified
ERROR: Another copy of the Inventory Collector is running. Please wait until it is complete. Terminating
tput: No value for $TERM and no -T specified
ERROR: Another copy of the Inventory Collector is running. Please wait until it is complete. Terminating
```

What version of Docker are you using?

**Comment by jose-delarosa** [comment]
In addition to the Docker version, please provide the following:
1. Dell server model
2. Docker run command

Thanks,

**Comment by thomasalley** [comment]
Thanks for checking, Jose. I just realized that I'm a goober and was trying to install this inside a VM on an R710. I'd say that's _probably_ going to be the issue, there.

**Comment by jose-delarosa** [comment]
That might be it :) I'll close it then.
