### ISSUE TITLE
Error with Centos 7 - PowerEdge R640

### ISSUE THREAD

**Issue by guillaume-gricourt** [jose-delarosa/docker-images#4]
Hi,
I've tried to run your image on PowerEdge R640 with Centos7 installed.
This is the error :
`DSM SA Shared Services is already stopped
Shutting down DSM SA Connection Service: [FAILED]

Stopping Systems Management Data Engine:
Stopping dsm_sa_snmpd: Not started[FAILED]
Stopping dsm_sa_eventmgrd: Not started[FAILED]
Stopping dsm_sa_datamgrd: Not started[FAILED]
Stopping Systems Management Device Drivers:
Stopping dell_rbu:[  OK  ]
Starting Systems Management Device Drivers:
Starting dell_rbu:[  OK  ]
Starting ipmi driver:
Already started[  OK  ]
Starting Systems Management Data Engine:
Failed to start because system is not supported
dsm_om_shrsvc: DSM SA Shared Services cannot start on an unsupported system. See the Dell Systems Software Support Matrix for a list of supported systems.
Starting DSM SA Connection Service: [  OK  ]
tail: cannot open '/opt/dell/srvadmin/var/log/openmanage/dcsys64.xml' for reading: No such file or directory
tail: no files remaining`

This is the config:
docker 
Version : 18.03.1-ce
API v : 1.37
Linux 
Version : Centos 7.4.1708
OMSA 
Version : 8.4

This is the command line 
docker run --privileged -d -p 1311:1311 --restart=always -v /lib/modules/`uname -r`:/lib/modules/`uname -r` --name=omsa84 jdelaros1/openmanage:latest

I've tried with successful with another server PowerEdge R630 on ubuntu server 14.04.
Have you an idea, what i am wrong ?
Thanks a lot,

**Comment by jose-delarosa** [comment]
Are you building the image yourself or are you pulling it from Docker Hub? If building it, what does your Dockerfile look like?

**Comment by guillaume-gricourt** [comment]
Hi,
I took your image from :
[docker hub jdelaros1](https://hub.docker.com/r/jdelaros1/openmanage/)
However it seems to old for R640

I tried 2 workarounds:
* build img from your omsa84 folder with dsu version 17.03.00
I got error with libsmbios.so.2 compatibility. I didn't found any solution to resolve it. 
* build it with the last DSU 18.12.00
When install it, i get this 
warning: %post(srvadmin-tomcat-9.2.0-3142.13664.el7.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package srvadmin-tomcat-9.2.0-3142.13664.el7.x86_64
These solutions didn't resolve it...
[#45](https://github.com/CentOS/sig-cloud-instance-images/issues/45)

Have you an idea to build an image with a dsu version greather than 16.02.00 ?

**Comment by guillaume-gricourt** [comment]
So...
I built image from this fork project 
[docker-dell-images](https://github.com/spkane/docker-dell-images)
and it's work ... i can't explain why ... 
Thanks
